const GET_DOGS = 'GET_DOGS';
const GET_DOGS_DETAIL = 'GET_DOGS_DETAIL';
const TEMPERAMENTOS = 'TEMPERAMENTOS';
const SEARCH_DOGS = 'SEARCH_DOGS';
const CREATE_DOG = 'CREATE_DOG';
const CREATE_TEMPERAMENTO = 'CREATE_TEMPERAMENTO';
const ORDENAR_ASC = 'ORDENAR_ASC';
const ORDENAR_DESC = 'ORDENAR_DESC';
const ORDENAR_MAS_PESADO ='ORDENAR_MAS_PESADO';
const ORDENAR_MAS_LIVIANO ='ORDENAR_MAS_LIVIANO';


module.exports = {
    GET_DOGS,
    GET_DOGS_DETAIL,
    SEARCH_DOGS,
    TEMPERAMENTOS,
    CREATE_DOG,
    CREATE_TEMPERAMENTO,
    ORDENAR_ASC,
    ORDENAR_DESC,
    ORDENAR_MAS_PESADO,
    ORDENAR_MAS_LIVIANO
}

