const GET_DOGS = 'GET_DOGS';
const GET_DOGS_DETAIL = 'GET_DOGS_DETAIL';
const TEMPERAMENTOS = 'TEMPERAMENTOS';
const SEARCH_DOGS = 'SEARCH_DOGS';
const CREATE_DOG = 'CREATE_DOG';
const CREATE_TEMPERAMENTO = 'CREATE_TEMPERAMENTO';
const ORDENAR_TEMPERAMENTO = 'ORDENAR_TEMPERAMENTO'
const ORDENAR_NAME = 'ORDENAR_NAME';

const ORDENAR_MAS_PESADO ='ORDENAR_MAS_PESADO';
const ORDENAR_MAS_LIVIANO ='ORDENAR_MAS_LIVIANO';


module.exports = {
    GET_DOGS,
    GET_DOGS_DETAIL,
    SEARCH_DOGS,
    TEMPERAMENTOS,
    CREATE_DOG,
    CREATE_TEMPERAMENTO,
    ORDENAR_TEMPERAMENTO,
    ORDENAR_NAME,
    ORDENAR_MAS_PESADO,
    ORDENAR_MAS_LIVIANO
}

